pizzas/urls.py
from django.urls import path
from . import views 

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza,name='pizza'),
    path('new_comment/<int:pizza_id>/', views.new_comment,name='new_comment'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images',blank=True)

    def __str__(self):
        return self.name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return self.name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'comments'

    def __str__(self):
        return self.text

pizzas/forms.py
from django import forms 

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta: 
        model = Comment
        fields = ['text']
        labels = {'text':''}

        widgets = {'text': forms.Textarea(attrs={'cols':80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .forms import CommentForm

# Create your views here.
def index(request):
    return render(request, 'pizzas/index.html')

from .models import Pizza

def pizzas(request):
    pizzas = Pizza.objects.order_by('name')

    context = {'pizzas':pizzas}

    return render(request, 'pizzas/pizzas.html', context)


def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    toppings = pizza.topping_set.order_by('name')

    comments = pizza.comment_set.order_by('date_added')

    context = {'pizza': pizza, 'toppings': toppings, 'comments': comments}

    return render(request, 'pizzas/pizza.html', context)

def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = CommentForm()

    else: 
        form = CommentForm(data=request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza 
            new_comment.save()
            form.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)

    
    context = {'form': form, 'pizza':pizza}
    return render(request, 'pizzas/new_comment.html',context)

pizzas/templates/pizzas/base.html
<p>
    <center>
        <a href="{% url 'pizzas:index' %}">Pizzeria</a>
        <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
    </center>
</p>

{% block content%}

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}

<style>
    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 50%;
    }
</style>

<h1 style="background-color:gold;">
    <center>Pizzeria!</center>
</h1>

<h2 style="background-color:orange;">
    <center>The Perfect Pizza Palace</center>
</h2>

<body style="background-color: orangered;">
    <img src="https://m.media-amazon.com/images/I/71EAIS3bUpL._AC_SX522_.jpg" alt="neon pizza" class="center">

</body>

{% endblock content %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<h1 style="background-color: gold;">
    <center><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></center>
</h1>

<body style="background-color: orangered;">
    <font size='+2'>
        <p>Add a new comment:</p>
    </font>

    <form action="{% url 'pizzas:new_comment' pizza.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">Add Comment</button>
    </form>
</body>
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

<style>
    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 50%;
    }
</style>

<h1 style="background-color: gold;">
    <center>Pizza: {{ pizza }}</center>
</h1>

<body style="background-color: orangered;">
    <img src=" {{pizza.image}}" alt="test" class="center">

    <font size='+2'>
        <p>Toppings:</p>
    </font>
    <ul>
        {% for topping in toppings %}
        <li>
            <p>{{ topping.name }}</p>

        </li>
        {% empty %}
        <li> There are no toppings for this pizza yet</li>
        {% endfor %}

    </ul>

    <font size='+2'>
        <p>Comments:</p>
    </font>

    <ul>
        {% for comment in comments %}
        <li>
            <p>{{ comment.text }}</p>
        </li>
        {% empty %}
        <li> There are no comments for this pizza yet</li>
        {% endfor %}
    </ul>

    <p>
        <a href="{% url 'pizzas:new_comment' pizza.id %}">Add new comment</a>
    </p>
</body>
{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<h1 style="background-color: gold;">
    <center>Pizza List</center>
</h1>

<body style="background-color: orangered;">
    <ul>
        {% for p in pizzas %}

        <li>
            <font size="+4"><a href="{% url 'pizzas:pizza' p.id %}">{{ p }}</a></font>
        </li>
        {% empty %}
        <li> No pizzas have been added yet.</li>

        {% endfor %}

    </ul>
</body>

{% endblock content %}